# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7d5448531f6cd4e95ad9890888c683ff38aeaf6bf6b13c99d8a6f2555b2663d48860470fb52ba9b771407858f75b06fa3339af7d565d208a450d58e7b831aa3

test:
  secret_key_base: 0347c9083225d6c01e62c6c261acbc679ab46aea93f8d3ebd191dc6fd0db0dd9980d805c022462cbd9374d0da004eb4de6515d3a5baa79d50b9690f5751db787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
